name: SonarQube Code Scan

on:
  workflow_dispatch:

jobs:
  SonarQube_Scan:
    name: Scan with UCSF SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Scan Plugins PHP Code
        uses: sonarsource/sonarqube-scan-action@v4.1.0
        env:
          SONAR_TOKEN: sqp_db041dcd2f5c1f5310d1a87bde0dde3c52b455fa
          SONAR_HOST_URL: https://sonarqube.ucsf.edu
        with:
          args: >
            -Dsonar.projectKey=ucsf-education_moodle_ab414c18-b81d-4ee0-9125-2904626af99b
            -Dsonar.language=php
            #-Dsonar.sources=mod,lib
            -Dsonar.sources=mod,lib/antivirus,customfield/field,files/converter,lib/mlbackend,blocks,question/type,question/behaviour,question/format,filter,lib/editor,lib/editor/atto/plugins,enrol,auth,admin/tool,admin/tool/log/store,availability/condition,calendar/type,message/output,course/format,dataformat,user/profile/field,report,course/report,grade/export,grade/import,grade/report,grade/grading/form,mnet/service,webservice,repository,portfolio,search/engine,media/player,plagiarism,cache/stores,cache/locks,theme,local,contentbank/contenttype,h5p/h5plib,question/bank
            -Dsonar.inclusions=**/*.php
            -Dsonar.exclusions=**/node_modules/**,**/dist/**,**/vendor/**,**/packages/**,**/*.xml,**/*.xsd,**/*.xsl,**/*.config
            -Dsonar.lang.patterns.xml=
            -Dsonar.lang.patterns.mule=
            -Dsonar.scanner.javaOpts=-Xmx8g
            -Dsonar.verbose=true
            
      - name: Scan JavaScript Code
        uses: sonarsource/sonarqube-scan-action@v4.1.0
        env:
          SONAR_TOKEN: sqp_db041dcd2f5c1f5310d1a87bde0dde3c52b455fa
          SONAR_HOST_URL: https://sonarqube.ucsf.edu
        with:
          args: >
            -Dsonar.projectKey=ucsf-education_moodle_ab414c18-b81d-4ee0-9125-2904626af99b
            -Dsonar.language=js
            -Dsonar.sources=.
            -Dsonar.inclusions=**/*.js,**/*.jsx
            -Dsonar.exclusions=**/dist/**,**/vendor/**,**/*.min.js
            -Dsonar.scanner.javaOpts=-Xmx5g
            -Dsonar.javascript.file.suffixes=.js,.jsx,.mocha.js,.spec.js,.test.js
            -Dsonar.verbose=true
