on:
  workflow_dispatch:

jobs:
  SonarQube_Scan:
    name: Scan with UCSF SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Shallow clones should be disabled for a better relevancy of analysis
      - uses: sonarsource/sonarqube-scan-action@v4.1.0
        env:
          SONAR_TOKEN: sqp_db041dcd2f5c1f5310d1a87bde0dde3c52b455fa
          SONAR_HOST_URL: https://sonarqube.ucsf.edu
        with:
          args: >
            -Dsonar.projectKey=ucsf-education_moodle_ab414c18-b81d-4ee0-9125-2904626af99b
            -Dsonar.exclusions=***/build/**,**/dist/**,**/node_modules/**,**/vendor/**,**/*.min.js,**/*.min.css,**/packages/**,**/tests/behat/**,**/*.xml,**/*.xsd,**/*.xsl,**/*.config
            -Dsonar.scanner.javaOpts=-Xmx4g
            -Dsonar.sources=mod
            -Dsonar.inclusions=**/*.php
