name: SonarQube Code Scan All
on:
  workflow_dispatch:
env:
  SONAR_TOKEN: sqp_db041dcd2f5c1f5310d1a87bde0dde3c52b455fa
  SONAR_HOST_URL: https://sonarqube.ucsf.edu
  SONAR_SCANNER_OPTS: -Xmx32g
  SQ_PROJECT_KEY: ucsf-education_moodle_ab414c18-b81d-4ee0-9125-2904626af99b  
jobs:
  SonarQube_Scan:
    name: Scan with UCSF SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Shallow clones should be disabled for a better relevancy of analysis
          
      - name: Scan Core Frontend Code
        uses: sonarsource/sonarqube-scan-action@v4.1.0
        with:
          args: >
            -Dsonar.projectKey=${{ env.SQ_PROJECT_KEY }}
            -Dsonar.lang.patterns.mule=-
            -Dsonar.excludePlugins=mule
            -Dsonar.exclusions=mod,lib/antivirus,customfield/field,files/converter,lib/mlbackend,blocks,question/type,question/behaviour,question/format,filter,lib/editor,enrol,auth,admin/tool,availability/condition,calendar/type,message/output,course/format,dataformat,user/profile/field,report,course/report,grade/export,grade/import,grade/report,grade/grading/form,mnet/service,webservice,repository,portfolio,search/engine,media/player,plagiarism,cache/stores,cache/locks,theme,local,contentbank/contenttype,h5p/h5plib,question/bank
            -Dsonar.inclusions=**/*.{js,jsx,ts,tsx,css,scss,xml,cass,mustache,json,html}
            -Dsonar.javascript.file.suffixes=.js,.jsx,.mocha.js,.spec.js,.test.js
            -Dsonar.language=js,css,xml,cass,mustache,json,ts,html 
            -Dsonar.javascript.file.suffixes=.js,.jsx,.ts,.tsx
            -Dsonar.typescript.file.suffixes=.ts,.tsx
            -Dsonar.css.file.suffixes=.css,.scss
            -Dsonar.html.file.suffixes=.html
            -Dsonar.mustache.file.suffixes=.mustache            
      - name: Scan Core PHP Code
        uses: sonarsource/sonarqube-scan-action@v4.1.0
        with:
          args: >
            -Dsonar.projectKey=${{ env.SQ_PROJECT_KEY }}
            -Dsonar.language=php
            -Dsonar.lang.patterns.mule=-
            -Dsonar.excludePlugins=mule
            -Dsonar.exclusions=mod,lib/antivirus,customfield/field,files/converter,lib/mlbackend,blocks,question/type,question/behaviour,question/format,filter,lib/editor,enrol,auth,admin/tool,availability/condition,calendar/type,message/output,course/format,dataformat,user/profile/field,report,course/report,grade/export,grade/import,grade/report,grade/grading/form,mnet/service,webservice,repository,portfolio,search/engine,media/player,plagiarism,cache/stores,cache/locks,theme,local,contentbank/contenttype,h5p/h5plib,question/bank
            -Dsonar.inclusions=**/*.php
      - name: Scan Plugins Code
        uses: sonarsource/sonarqube-scan-action@v4.1.0
        with:
          args: >
            -Dsonar.projectKey=${{ env.SQ_PROJECT_KEY }}
            -Dsonar.lang.patterns.mule=-
            -Dsonar.excludePlugins=mule
            -Dsonar.sources=mod,lib/antivirus,customfield/field,files/converter,lib/mlbackend,blocks,question/type,question/behaviour,question/format,filter,lib/editor,enrol,auth,admin/tool,availability/condition,calendar/type,message/output,course/format,dataformat,user/profile/field,report,course/report,grade/export,grade/import,grade/report,grade/grading/form,mnet/service,webservice,repository,portfolio,search/engine,media/player,plagiarism,cache/stores,cache/locks,theme,local,contentbank/contenttype,h5p/h5plib,question/bank
          
